INSERT INTO AUX_AAMT_V
(Code, NAME_DE, NAME_FR, NAME_IT, STRASSE_DE, STRASSE_FR, STRASSE_IT, HAUS_NR, PLZ, ORT_DE, ORT_FR, ORT_IT, TELEFON, FAX, EMAIL)
VALUES (6668705, 'NAME_DE', 'NAME-_FR', 'NAME_IT', 'STRASSE_DE', 'STRASSE_FR', 'STRASSE_IT', 'HAUS_NR', 'PLZ', 'ORT_DE', 'ORT_FR', 'ORT_IT', '00419999999', '00419999999', 'email@example.org');
INSERT INTO AUX_AAMT_V
(Code, NAME_DE, NAME_FR, NAME_IT, STRASSE_DE, STRASSE_FR, STRASSE_IT, HAUS_NR, PLZ, ORT_DE, ORT_FR, ORT_IT, TELEFON, FAX, EMAIL)
VALUES (6668706, 'NAME_DE2', 'NAME-_FR2', 'NAME_IT2', 'STRASSE_DE2', 'STRASSE_FR2', 'STRASSE_IT2', 'HAUS_NR2', 'PLZ', 'ORT_DE', 'ORT_FR', 'ORT_IT', '00419999999', '00419999995', 'email2@example.org');
INSERT INTO AUX_AAMT_V
(Code, NAME_DE, NAME_FR, NAME_IT, STRASSE_DE, STRASSE_FR, STRASSE_IT, HAUS_NR, PLZ, ORT_DE, ORT_FR, ORT_IT, TELEFON, FAX, EMAIL)
VALUES (6668707, 'NAME_DE3', 'NAME-_FR3', 'NAME_IT3', 'STRASSE_DE3', 'STRASSE_FR3', 'STRASSE_IT3', 'HAUS_NR3', 'PLZ', 'ORT_DE', 'ORT_FR', 'ORT_IT', '00419999999', '00419999996', 'email3@example.org');
