version: '2'
services:
    referenceservice-elasticsearch:
        image: elasticsearch:6.5.0
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false
            - discovery.type=single-node
            - network.host=0.0.0.0
            - cluster.name=elasticsearch
