spring:
    jpa:
        open-in-view: false
        hibernate:
            # async creation of tables using liquibase
            # due to async creation of tables using liquibase we need to disable ddl-auto: verify
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.jdbc.lob.non_contextual_creation: true
            hibernate.id.new_generator_mappings: true
            hibernate.generate_statistics: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            hibernate.cache.hazelcast.instance_name: referenceservice
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML
    liquibase:
        change-log: classpath:/config/liquibase/master.xml
    task:
        execution:
            thread-name-prefix: refs-async
            pool:
                core-size: 2
                max-size: 50
                queue-capacity: 10000
        scheduling:
            thread-name-prefix: refs-scheduler
            pool:
                size: 1

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always

server:
    servlet:
        session:
            cookie:
                http-only: true

info:
    project:
        version: #project.version#
