server:
    port: 8082

spring:
    profiles:
        include: dev, swagger
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5434/referenceservice
        username: referenceservice
        password: secret
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes: localhost:9300
    liquibase:
        contexts: dev
        drop-first: false
    messages:
        cache-duration: 1s
    thymeleaf:
        cache: false
    zipkin:
        enabled: false
    sleuth:
        enabled: false
        annotation:
            enabled: false

jhipster:
    cache:
        hazelcast:
            management-center:
                enabled: false
                url: http://localhost:8180/hazelcast-mancenter
                update-interval: 3
# ===================================================================
# Logging
# ===================================================================
logging:
    level:
        ROOT: INFO
        liquibase.integration.spring: DEBUG
        io.github.jhipster: DEBUG
        ch.admin.seco.service.reference: DEBUG

