version: '3'
services:
    jhipster-registry:
        image: jhipster/jhipster-registry:v3.2.4
        volumes:
            - ./central-server-config:/central-config
        # When run with the "dev" Spring profile, the JHipster Registry will
        # read the config from the local filesystem (central-server-config directory)
        # When run with the "prod" Spring profile, it will read the configuration from a Git repository
        # See http://www.jhipster.tech/microservices-architecture/#registry_app_configuration
        environment:
            - SPRING_PROFILES_ACTIVE=dev,native,swagger
            - SECURITY_USER_PASSWORD=admin
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/localhost-config/
        # - GIT_URI=https://github.com/jhipster/jhipster-registry/
        # - GIT_SEARCH_PATHS=central-config
        ports:
            - 8761:8761

    elasticsearch:
        image: elasticsearch:6.5.0
        # volumes:
        #     - ~/volumes/jhipster/referenceservice/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
        networks: ['elasticstack']
        environment:
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false
            - network.host=0.0.0.0
            - discovery.type=single-node
            - cluster.name=elasticsearch

    kibana:
        image: kibana:6.5.0
        container_name: kibana
        hostname: kibana
        ports: ['5601:5601']
        networks: ['elasticstack']
        depends_on: ['elasticsearch']
        #restart: on-failure
        environment:
            - elasticsearch.url=http://elasticsearch:9200
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false

    postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/referenceservice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=referenceservice
            - POSTGRES_PASSWORD=
        ports:
            - 5434:5432

    oracle-xe:
        build: oracle-xe
        ports:
            - 11521:1521

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka:1.1.0
        ports:
            - "9092:9092"
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
            - KAFKA_ADVERTISED_PORT=9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

        depends_on:
            - zookeeper

    dataflow-server:
        image: springcloud/spring-cloud-dataflow-server-local:1.7.4.RELEASE
        container_name: dataflow-server
        ports:
            - "9393:9393"
            - "9000-9010:9000-9010"
        environment:
            - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers=kafka:9092
            - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.zkNodes=zookeeper:2181
        depends_on:
            - kafka
        #volumes:
           # - ~/.m2:/root/.m2

    referenceservice-hazelcast-management-center:
        image: hazelcast/management-center:3.11.1
        ports:
            - 8180:8080


networks:
    elasticstack:

